In [1]:
# pandas is used for data cleaning, preprocessing, data extraction, used as excel button

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\new\Desktop\grades.csv")

In [3]:
df.columns = df.columns.str.replace('"','').str.strip()

print(df.columns)

Index(['Last name', 'First name', 'SSN', 'Test1', 'Test2', 'Test3', 'Test4',
       'Final', 'Grade'],
      dtype='object')

In [4]:
df.head() #

,Last name,First name,SSN,Test1,Test2,Test3,Test4,Final,Grade
0,Alfalfa,"""Aloysius""","""123-45-6789""",40.0,90.0,100.0,83.0,49.0,"""D-"""
1,Alfred,"""University""","""123-12-1234""",41.0,97.0,96.0,97.0,48.0,"""D+"""
2,Gerty,"""Gramma""","""567-89-0123""",41.0,80.0,60.0,40.0,44.0,"""C"""
3,Android,"""Electric""","""087-65-4321""",42.0,23.0,36.0,45.0,47.0,"""B-"""
4,Bumpkin,"""Fred""","""456-78-9012""",43.0,78.0,88.0,77.0,45.0,"""A-"""

In [5]:
df.shape

(16, 9)

In [6]:
df.columns

Index(['Last name', 'First name', 'SSN', 'Test1', 'Test2', 'Test3', 'Test4',
       'Final', 'Grade'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Last name   16 non-null     object
 1   First name  16 non-null     object
 2   SSN         16 non-null     object
 3   Test1       16 non-null     object
 4   Test2       16 non-null     float64
 5   Test3       16 non-null     float64
 6   Test4       16 non-null     float64
 7   Final       16 non-null     object
 8   Grade       15 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.3+ KB

In [8]:
#selecting 
#single column

df['Grade']

0        "D-"
1        "D+"
2         "C"
3        "B-"
4        "A-"
5        "C-"
6         "F"
7        "B+"
8         NaN
9        "A+"
10       "D+"
11       "C+"
12       "B-"
13       "B-"
14        "B"
15        "C"
Name: Grade, dtype: object

In [9]:
#selecting multiple columns
df[['First name','Grade']]

          First name    Grade
0         "Aloysius"     "D-"
1       "University"     "D+"
2           "Gramma"      "C"
3         "Electric"     "B-"
4             "Fred"     "A-"
5            "Betty"     "C-"
6            "Cecil"      "F"
7              "Bif"     "B+"
8           "Andrew"      NaN
9              "Jim"     "A+"
10             "Art"     "D+"
11             "Jim"     "C+"
12             "Ima"     "B-"
13           "Benny"     "B-"
14             "Boy"      "B"
15          "Harvey"      "C"

In [10]:
#select by row index
df.iloc[0]

Last name              Alfalfa
First name          "Aloysius"
SSN              "123-45-6789"
Test1                     40.0
Test2                     90.0
Test3                    100.0
Test4                     83.0
Final                     49.0
Grade                     "D-"
Name: 0, dtype: object

In [11]:
df.iloc[0:3]

,Last name,First name,SSN,Test1,Test2,Test3,Test4,Final,Grade
0,Alfalfa,"""Aloysius""","""123-45-6789""",40.0,90.0,100.0,83.0,49.0,"""D-"""
1,Alfred,"""University""","""123-12-1234""",41.0,97.0,96.0,97.0,48.0,"""D+"""
2,Gerty,"""Gramma""","""567-89-0123""",41.0,80.0,60.0,40.0,44.0,"""C"""

In [12]:
df[df['Test2']>90]

,Last name,First name,SSN,Test1,Test2,Test3,Test4,Final,Grade
1,Alfred,"""University""","""123-12-1234""",41.0,97.0,96.0,97.0,48.0,"""D+"""

In [13]:
# how to add new column

cols = ['Test1','Test2','Test3','Test4']
df[cols] = df[cols].apply(pd.to_numeric, errors ='coerce')

In [14]:
df['Average'] = df[cols].mean(axis=1)

In [15]:
# how to add new column

# how to add new column

df['total'] = df[cols].sum(axis=1)
df['Average'] = df[cols].mean(axis=1)
df.head()
df['Average'] = df[cols].mean(axis=1)
df.head()

,Last name,First name,SSN,Test1,Test2,Test3,Test4,Final,Grade,Average,total
0,Alfalfa,"""Aloysius""","""123-45-6789""",40.0,90.0,100.0,83.0,49.0,"""D-""",78.25,313.0
1,Alfred,"""University""","""123-12-1234""",41.0,97.0,96.0,97.0,48.0,"""D+""",82.75,331.0
2,Gerty,"""Gramma""","""567-89-0123""",41.0,80.0,60.0,40.0,44.0,"""C""",55.25,221.0
3,Android,"""Electric""","""087-65-4321""",42.0,23.0,36.0,45.0,47.0,"""B-""",36.50,146.0
4,Bumpkin,"""Fred""","""456-78-9012""",43.0,78.0,88.0,77.0,45.0,"""A-""",71.50,286.0

In [16]:
#sorting data

df.sort_values(by = 'Average', ascending = False).head(5)

,Last name,First name,SSN,Test1,Test2,Test3,Test4,Final,Grade,Average,total
8,Airpump,"""Andrew""","""223-45-6789""",NaN,90.0,100.0,83.0,"""A""",NaN,91.00,273.0
1,Alfred,"""University""","""123-12-1234""",41.0,97.0,96.0,97.0,48.0,"""D+""",82.75,331.0
0,Alfalfa,"""Aloysius""","""123-45-6789""",40.0,90.0,100.0,83.0,49.0,"""D-""",78.25,313.0
5,Rubble,"""Betty""","""234-56-7890""",44.0,90.0,80.0,90.0,46.0,"""C-""",76.00,304.0
4,Bumpkin,"""Fred""","""456-78-9012""",43.0,78.0,88.0,77.0,45.0,"""A-""",71.50,286.0

In [17]:
# sort by grade & final
df['Grade'].value_counts()

Grade
"B-"    3
"C"     2
"D+"    2
"D-"    1
"A-"    1
"C-"    1
"F"     1
"B+"    1
"A+"    1
"C+"    1
"B"     1
Name: count, dtype: int64

In [18]:
df['Grade'].unique()

array(['   "D-"', '   "D+"', '   "C"', '   "B-"', '   "A-"', '   "C-"',
       '   "F"', '   "B+"', nan, '   "A+"', '   "C+"', '   "B"'],
      dtype=object)

In [20]:
# lets find average marks per grade

df.groupby('Grade')['Average'].mean()

Grade
"A+"    60.50
"A-"    71.50
"B"     12.75
"B+"    34.00
"B-"    48.25
"C"     37.75
"C+"    26.75
"C-"    76.00
"D+"    64.50
"D-"    78.25
"F"     14.75
Name: Average, dtype: float64

In [21]:
# mapping is done in pandas

In [ ]:
// task-1 mapping in pandas

grade_map = {'A': 'Excellent', 'B': 'Good', 'C': 'Average', 'D': 'Poor', 'F': 'Fail'}
df['Grade_Description'] = df['Grade'].map(grade_map)
df.head()

,Last name,First name,SSN,Test1,Test2,Test3,Test4,Final,Grade,Average,total,Grade_Description
0,Alfalfa,"""Aloysius""","""123-45-6789""",40.0,90.0,100.0,83.0,49.0,"""D-""",78.25,313.0,NaN
1,Alfred,"""University""","""123-12-1234""",41.0,97.0,96.0,97.0,48.0,"""D+""",82.75,331.0,NaN
2,Gerty,"""Gramma""","""567-89-0123""",41.0,80.0,60.0,40.0,44.0,"""C""",55.25,221.0,NaN
3,Android,"""Electric""","""087-65-4321""",42.0,23.0,36.0,45.0,47.0,"""B-""",36.50,146.0,NaN
4,Bumpkin,"""Fred""","""456-78-9012""",43.0,78.0,88.0,77.0,45.0,"""A-""",71.50,286.0,NaN